# Generated by Django 3.2 on 2021-05-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
