# Generated by Django 3.2 on 2021-08-23 18:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_container_command_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='port',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.CharField(default=api.models.create_id, editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
