# Generated by Django 3.2 on 2021-08-23 18:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20210823_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Container',
            new_name='Server',
        ),
    ]
