# Generated by Django 3.2 on 2021-09-01 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_rename_container_id_server_server_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sftp_port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users allowed to manage this server'),
        ),
    ]
