# Generated by Django 3.2 on 2021-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_server_sftp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='host',
            field=models.CharField(default='alwin.sweet', max_length=255),
        ),
    ]
