# Generated by Django 3.2.8 on 2021-10-14 13:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_server_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_id',
            field=models.CharField(default=api.models.create_id, editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='sftp_port',
            field=models.IntegerField(unique=True),
        ),
    ]
