version: "3"
services:
  app:
    build: .
    env_file: .env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-static:/var/www/static
    ports:
      - "127.0.0.1:8000:8000"