version: "3"
services:
  backend:
    build: backend
    env_file: .env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "containerpanel"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "containerpanel"


  frontend:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    ports:
      - 80:8002
    restart: always

