version: "3"
services:
  backend:
    build: backend
    env_file: .env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    ports:
      - 80:8002
    restart: always

