# Generated by Django 3.2 on 2021-05-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='id',
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
