# Generated by Django 3.2 on 2021-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_container_container_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=1024)),
                ('env', models.CharField(max_length=1024)),
                ('volumes', models.CharField(max_length=1024)),
                ('ports', models.CharField(max_length=1024)),
            ],
        ),
    ]
