# Generated by Django 3.2 on 2021-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210901_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sftp_password',
            field=models.CharField(default='rewrt42tg4h5h', max_length=64),
            preserve_default=False,
        ),
    ]
