# Generated by Django 3.2 on 2021-05-03 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0002_auto_20210503_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users allowed to manage this container'),
        ),
    ]
