# Generated by Django 3.2 on 2021-06-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_container_command_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='command_prefix',
            field=models.CharField(max_length=400),
        ),
    ]
