name: Backend Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: backend
        file: backend/Dockerfile
        push: true
        tags: ghcr.io/niwla23/containerpanel-backend:latest
