name: Frontend Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: proxy/Dockerfile
        push: true
        tags: ghcr.io/niwla23/containerpanel-frontend:latest
